version: "3.8"

services:
  backend:
    image: holmst33n/backend:latest # Use Docker Hub image
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=${CONNECTION_STRING} # Use environment variable for connection string
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: holmst33n/frontend:latest # Use Docker Hub image
    ports:
      - "80:80"
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Use environment variable for password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
