services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: Development
        CONNECTION_STRING: ${CONNECTION_STRING}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=${CONNECTION_STRING}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  test-runner:
    build:
      context: ./backend
      dockerfile: Dockerfile.test # A separate Dockerfile for tests
    depends_on:
      - backend
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    command: dotnet test --logger:trx

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
