# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI with tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', '**/docker-compose.yml') }}
          restore-keys: |
            docker-${{ runner.os }}-

      - name: Load Docker cache
        run: |
          mkdir -p /tmp/.docker
          if [[ -f /tmp/.docker/layers.tar ]]; then
            docker load -i /tmp/.docker/layers.tar || echo "No cached layers found"
          fi

      - name: Build and Start Services
        run: docker-compose up -d --build

      - name: Run Tests
        run: |
          docker-compose exec -T backend dotnet test

      - name: Save Docker cache
        run: |
          mkdir -p /tmp/.docker
          docker save $(docker-compose config | sed -n '/image:/ s/.* //p') -o /tmp/.docker/layers.tar

