name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.HUB_USER}}
          password: ${{secrets.HUB_PASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build Frontend -f Frontend/Dockerfile -t kunsthavn/frontend:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/kunsthavn/frontend:latest
